vars:
  stage: develop_base

components:
  terraform:
    base:
      backend_type: s3
      backend:
        s3:
          bucket: "Demo-terraform-backend-storage"
          use_lockfile: true
          region: "ap-southeast-1"
          key: "develop_base.tfstate"
          encrypt: true
      vars:
        environment: "develop"
        aws_id: "118955426917"
        region: "ap-southeast-1"
        vpc_name: "develop-vpc"
        vpc_cidr: "10.0.0.0/16"
        create_nat: true
        azs: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
        public_subnet_cidr: ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
        private_subnet_cidr: ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
        acm_arn: "arn:aws:acm:ap-southeast-1:118955426917:certificate/4364b001-f838-4a36-b51c-18fbbad7fe9b"
