vars:
  stage: preprod_base

components:
  terraform:
    base:
      backend_type: s3
      backend:
        s3:
          bucket: "Demo-terraform-backend-storage"
          use_lockfile: true
          region: "ap-southeast-1"
          key: "preprod_base.tfstate"
          encrypt: true
      vars:
        environment: "preprod"
        aws_id: "xxxxxxxxxxxxxxxxx"
        region: "ap-southeast-1"
        vpc_name: "preprod-vpc"
        vpc_cidr: "10.2.0.0/16"
        create_nat: true
        azs: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
        public_subnet_cidr: ["10.2.1.0/24", "10.2.2.0/24", "10.2.3.0/24"]
        private_subnet_cidr: ["10.2.4.0/24", "10.2.5.0/24", "10.2.6.0/24"]
        acm_arn: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
