vars:
  stage: packer


components:
  packer:
    Demo-ami:
      vars:
        region: "ap-southeast-1"
        ami_prefix: "Demo-base"
        environment: "image"
        instance_type: "t3a.small"
        install_nginx: true
        install_docker: true
        install_docker_compose: true
        install_mysql_client: true
        install_mysql_server: true
