vars:
  stage: db_prod



components:
  terraform:
    database:
      backend_type: s3
      backend:
        s3:
          bucket: "Demo-terraform-backend-storage"
          use_lockfile: true

          region: "ap-southeast-1"
          key: "db_prod.tfstate"
          encrypt: true
      vars:
        environment: "prod"
        aws_id: "521690816778"
        region: "ap-southeast-1"
        app_security_group_id: "sg-0c1234567890abcdef"
        vpc_id: "vpc-0c1234567890abcdef"
        private_subnet_ids: ["subnet-0c1234567890abcdef", "subnet-0c1234567890abcdef"]
        parameter_group_name: "Demo-prod-db-parameter-group"
        parameter_group_family: "mysql8.0"
        db_username: "Demo_admin"
        db_name: "Demo_prod_db"
        allocated_storage: 20
        max_allocated_storage: 100
        instance_class: "db.4g.micro" 
        engine: "mysql"
        engine_version: "8.0"
        db_identifier: "Demo-prod-db"
        avail_zone: "ap-southeast-1a"
        storage_type: "gp2"
        multi_az: false
